---
- hosts: dev
  become: true
  vars:
    docker_image: hashith/node_devops:latest
    container_name: node-container
    app_repo: https://github.com/code-sagar/nodejs-demo.git
    app_dest: /var/www/html/nodejs-demo
    docker_hub_username: hashith
    docker_hub_password: da19sun95

  tasks:
    - name: Clone Node.js app repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dest }}"

    - name: Docker Login
      docker_login:
        registry_url: https://hub.docker.com/repository/docker/hashith/node_devops/general
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Pull the Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Ensure old container is absent
      docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes

    - name: Run the Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        ports:
          - "8080:8080"
