---
- hosts: dev
  become: true
  vars:
    docker_image: hashith/vojo_admin_front:latest
    container_name: node-container
    app_repo: https://github.com/code-sagar/nodejs-demo.git
    app_dest: /var/www/html/nodejs-demo
    docker_hub_username:
    docker_hub_password: 
  tasks:
    - name: Clone Node.js app repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dest }}"

    - name: Docker Login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Pull the Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Ensure old container is absent
      docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: yes

    - name: Run the Docker container
      command: docker run -d -p 8080:8080 --name {{ container_name }} {{docker_image}}
